name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  ACR_NAME: 77security
  IMAGE_NAME: identity
  AKS_CLUSTER: 77security
  RESOURCE_GROUP: Resourcegroup

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group $RESOURCE_GROUP \
            --name $AKS_CLUSTER

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-service ./helm/my-service \
            --set image.tag=${{ github.sha }}
