name: Trigger auto deployment for identity

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/identity-AutoDeployTrigger-25c4aeba-54fa-4ec1-a7f2-2fd7cd996466.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IDENTITY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IDENTITY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IDENTITY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 77security.azurecr.io
          registryUsername: ${{ secrets.IDENTITY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IDENTITY_REGISTRY_PASSWORD }}
          containerAppName: identity
          resourceGroup: Resourcegroup
          imageToBuild: 77security.azurecr.io/identity:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


